### ISSUE TITLE
[Documentation]:  https://epcced.github.io/eidf-docs/services/jhub/quickstart/   Managed Jupyter Hub docs are blank

### ISSUE THREAD

**Issue by clairbarrass** [EPCCed/eidf-docs#118]
### Issue

 https://epcced.github.io/eidf-docs/services/jhub/quickstart/   Managed Jupyter Hub docs are blank
 
 These pages should at least say "Coming soon" or similar

**Comment by robertn01** [comment]
To report or rather re-iterate this one. I have recently come across the same issue as part of my currently assigned tasks.
Kostas and I discussed and suggest that it be hidden on the userdoc until fleshed out and the service is launched.
