### ISSUE TITLE
[Documentation]: Missing docs for SDF-CS1

### ISSUE THREAD

**Issue by aturner-epcc** [EPCCed/eidf-docs#12]
### What documentation issue are you reporting

Missing Documentation

### Issue

As the Cerebras system is already available to people, it would be good to have some documentation as soon as possible that covers:

* How to request an account on SDF-CS1 via EPCC SAFE (may be useful to point to SAFE docs at: https://epcced.github.io/safe-docs/)
* How to log on and transfer data to SDF-CS1 via SSH
* How to setup models for use with CS-1
* How to use Slurm to submit jobs to use CS-1

**Comment by nickaj** [comment]
These are now in place; closing.
