### ISSUE TITLE
[Documentation]: URL structures

### ISSUE THREAD

**Issue by wood-chris** [EPCCed/eidf-docs#18]
### What documentation issue are you reporting

Formatting

### Issue

**Issue Reported**

This may be a result of the templating system used, but several directory level URLs (which might be useful) result in 404 - e.g. 

https://epcced.github.io/eidf-docs/services/virtualmachines/
https://epcced.github.io/eidf-docs/services/datacatalogue/

**Comment by agngrant** [comment]
This is a function of the templating system it looks like, replicated in readthedocs as well for similar style layouts.

**Comment by aturner-epcc** [comment]
If you put an `index.md` file in the directory then you will get a page that can be rendered. This is how we get around this issue on the ARCHER2 docs.
