### ISSUE TITLE
[Documentation]: The first time you login on to the VM you MUST go through the vdi

### ISSUE THREAD

**Issue by marioa** [EPCCed/eidf-docs#70]
### What documentation issue are you reporting

Incomplete Documentation

### Issue

If you login directly using:
```bash
$ ssh -J [SAFE-username]@eidf-gateway.epcc.ed.ac.uk [VM-username]@[VM/IP]
```
it will fail with a slightly cryptic:
```
Enter passphrase for key '/Users/mario/.ssh/id_rsa':
mario-out@eidf-gateway.epcc.ed.ac.uk's password:
channel 0: open failed: administratively prohibited: open failed
stdio forwarding failed
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
```
Even though the correct pass phrase and password have been used. In order for the ssh access to succeed you MUST apparently go through the vdi first where your password will be reset BEFORE you can login to the VM directly. The documentation should state this.

**Comment by akrause2014** [comment]
Include link to [http://localhost:5000/eidf-docs/services/virtualmachines/quickstart/#accessing-a-vm](https://epcced.github.io/eidf-docs/services/virtualmachines/quickstart/#accessing-a-vm) or copy the warning box from there to the SSH page.

**Comment by nickaj** [comment]
This is no longer true - with the Set Password mechanism, users are directed to set a password before first login and therefore won't hit this problem.
