### ISSUE TITLE
[Documentation]: 

### ISSUE THREAD

**Issue by djwhiteastro** [EPCCed/eidf-docs#72]
### What documentation issue are you reporting

Incorrect Documentation

### Issue

"Known Issues" section is incorrect:

1. Users can be given sudo rights by PIs if requested
2. There is a known issue with Firefox on current Ubuntu builds due to an issue with snapd not working with non-standard home directories (though this may be fixed soon)

**Comment by akrause2014** [comment]
Issue with Firefox is resolved with recent update of snapd version >= 2.59.1

New VMs will automatically be configured with the snapd system option for home directories.
